language: node_js
node_js:
- iojs
- '7'
env:
  global:
    secure: J3NeriWDx6kQRuokOOh6Usb9lMQdnrPoHfsJ7f9B8ynNOO+g+q13valH/sCs5l1rCBiojnRfakAmUQb2EfcrnGlouA6KzYUtcpmYSbt5VgEIR9o3Nc/rzHUl5fFihh4Evg7FpJzfdAwRGw3qZdmKg55jXjpepO822+hAaXoVCRYDOBBZfLUihIO6F586HsoOneZt2e4Lt7BECGOgjEEY9O+t6Bk3PoKXEOtpGGmpVI7wYNTuee8W6hhmw5XDxNgH+a9ZNHiesRCnijnhoUnFKjpHTHoqPnf9P4F8wHCRpyXr0giZ4OFlvT+MFsaadUU7QJaNn/POSiDAMKNRNsxBGYk9Br2vytQ5ZfzNtopIF5tDMh6I7N6OW+MdJ4zG6fI3GtPHPTi562UdYqIVrPf1x/yCCC5w2g1SMSpyIHAwD4T3Ng/03DeSqJOM59fhA66LZPculwXSV7Pw4/oxTxxdYb8kZTk6e4KnQY87JZLdQLSWhKRYZrqhzuYZzz+PUQ8YkNQYen8F3jtJQmpIRIgQ0guGTzxAXodx7R7MwHymNVgtfAfkV2ZJXzQYTotLSn9Rne12VtDOCRwOWUoEyBHMdrqFLk/MTQJf2eUBwqqlYFj+G0ep7hXKc5ft+oqj4skqQA6tqDau6crGcbNwFmhJlSPXM3T9NnjmefOiCG4LhA4=
