language: node_js
node_js:
- iojs
- '7'
env:
  global:
deploy: 
  provider: firebase
  token:
    secure: Zi9mW5E668qkgoV83JWhVqKIiTTAaWDKWV7LfwRq/WgZcq+Y03fAKPgWb6YBrB4cIys2Jb0zE8+3S6B9AtEb3Sgf9M/LvEz9BPbCsfMwLbTl5Id1dzoOMEffbFydOk9szReky+uGyDSFlk1Ol+hAga4zam5YdGuuszh2uOtstqFBiwOT1a6tcnE+DvXnAgiKeuf5b/Y5PR2i66FqLhXtU3rd4LH2moezHi3Xfi5fhO0t0RssA0LzX+NwN42A2A59myuA0unhTerNXOzP5fJVEegWln/qn29mcWBTFQFelG5bjhk9dEjfxfjshV/QokRv67r/Bs8uUQ2cujgh2TjDzNjoMNmCzJrssQ7+dzPAXJeoUK8y+f1V9oWEj01tNPA300xeN5xROc+Y4WWWQuJuDkm8KxaNjhY5SsCCW8APon1MzkE2xl8kAFXfYH2OGHs6xf12j5aQi5xuMc8G/p4wSkqypU3VCxuWEwclWYCg+BAj8RDnepm/LR5q4OvEqnL1By/qR8Bo0/d2mLWBAvLt7eOKpCm0vtei8WvcGFPHszrwtbAMG9OIq6amE3TDcktTbCYMKwEN3ZWWrQcvsvSsQJcSFdArYVy07Jut3aXNJHsq6SxrmPjJYCCuUC0N2m2e81fEX+c2LDpYY0AIWq+mOEWpmeMuuSvb/NYDOXvL938=
  project: "decideupserver"
